/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    // application
    java
    war
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(libs.spring.context)
    implementation(libs.jakarta.annotation)
    implementation(libs.jakarta.persistence.api)
    implementation(libs.spring.aop)
    implementation(libs.spring.aspects)
    implementation(libs.spring.orm)
    implementation(libs.hikari)
    implementation(libs.hibernate.core)
    implementation(libs.hibernate.hikaricp)
    implementation(libs.slf4j.api)
    implementation(libs.logback.core)
    implementation(libs.logback.classic)
    implementation(libs.h2)
    implementation(libs.spring.data.jpa)
    implementation("org.springframework:spring-jdbc:6.2.2")
    implementation("org.springframework:spring-webmvc:6.2.4")
    implementation("org.springframework:spring-web:6.2.4")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.15.0")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.15.2")
    implementation("com.fasterxml.jackson.core:jackson-core:2.15.2")
		implementation("org.thymeleaf:thymeleaf:3.1.2.RELEASE")
		implementation("org.thymeleaf:thymeleaf-spring6:3.1.2.RELEASE")
    implementation("org.springframework.security:spring-security-web:6.2.2")
    implementation("org.springframework.security:spring-security-config:6.2.2")
		implementation("org.thymeleaf.extras:thymeleaf-extras-springsecurity6:3.1.1.RELEASE")
    providedCompile("jakarta.servlet:jakarta.servlet-api:6.1.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.war {
    archiveFileName.set("pet-shop-app.war")
}

// application {
//     // Define the main class for the application.
//     mainClass = "ru.bsuedu.cad.lab.app.ClientApp"
// }

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
