/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    java
    war
		jacoco
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
		implementation(libs.spring.context)
		implementation(libs.spring.orm)
		implementation(libs.hikari)
		implementation(libs.hibernate.hikaricp)
		implementation(libs.hibernate.core)
		implementation(libs.jakarta.persistence.api)
		implementation(libs.slf4j.api)
		implementation(libs.logback.core)
    implementation(libs.logback.classic)
    runtimeOnly(libs.h2)
    implementation("org.springframework.data:spring-data-jpa:3.2.5")
		implementation("org.springframework:spring-webmvc:6.2.4")
		implementation("org.springframework:spring-web:6.2.4")
    providedCompile("jakarta.servlet:jakarta.servlet-api:6.1.0")
		implementation("com.fasterxml.jackson.core:jackson-databind:2.15.0")
		implementation("org.thymeleaf:thymeleaf:3.1.2.RELEASE")
		implementation("org.thymeleaf:thymeleaf-spring6:3.1.2.RELEASE")
		implementation("org.springframework.security:spring-security-web:6.2.2")
    implementation("org.springframework.security:spring-security-config:6.2.2")

		testImplementation("org.junit.jupiter:junit-jupiter-api:5.11.1")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.11.1")
    testImplementation("org.mockito:mockito-core:5.17.0")
    testImplementation("org.mockito:mockito-junit-jupiter:5.17.0")
    testImplementation("org.assertj:assertj-core:3.25.3")
    testImplementation("org.springframework:spring-test:6.2.2")
		testImplementation("org.springframework:spring-test:6.2.2")
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.2")
    testImplementation("com.h2database:h2:2.2.224")
		runtimeOnly("com.h2database:h2")
}
 
// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}


tasks.named<Test>("test") {
    useJUnitPlatform()
    finalizedBy(tasks.jacocoTestReport)
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)
    reports {
        xml.required = true
        csv.required = true
        html.required = true
    }
}

tasks.war {
    archiveFileName.set("petshop.war")
}

