/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.bsuedu.cad.lab;

import java.io.IOException;
import java.text.ParseException;

public interface Renderer {
  public void render() throws NumberFormatException, IOException, ParseException;
}